Fix find_by when passed an invalid id
```rb
 # Assuming there is no country with id 2.
Country.find_by(id: 2, name: "UK")
```

Before:
> Exception: NoMethodError: undefined method `[]' for nil:NilClass (...) active_hash/base.rb:185:in `block in match_options?'

After:
> ActiveHash::RecordNotFound: Couldn't find Country