Fix no method error on lib/active_hash/base.rb
```
ActiveHash Base #cache_key should use the class's cache_key and id
Failure/Error: Country.first.cache_key.should == 'countries/1'
NoMethodError:
  undefined method `empty?' for Country:Class

ActiveHash Base #cache_key should use the record's updated_at if present
Failure/Error: Country.first.cache_key.should == "countries/1-#{timestamp.to_s(:number)}"
NoMethodError:
  undefined method `empty?' for Country:Class

ActiveHash Base #cache_key should use "new" instead of the id for a new record
Failure/Error: Country.new(:id => 1).cache_key.should == 'countries/new'
NoMethodError:
  undefined method `empty?' for Country:Class
```