Rubinius support bug fixes
Fix error (mismatch of error description):

2) ActiveHash Base custom finders find_by_<field_one>_and_<field_two>! for fields the class doesn't have raises a NoMethodError
     Failure/Error: lambda {
       expected NoMethodError with "undefined method `find_by_name_and_shoe_size!' for Country:Class", got #<NoMethodError: undefined method `find_by_name_and_shoe_size!' on Country (Class)>