require reflection_extensions when ActiveRecordExtensions is extended
`extend ActiveHash::Associations::ActiveRecordExtensions` does not require 'reflection_extensions'
so the following error occurs when `compute_class` is called in Rails 7.

```
ArgumentError: Rails couldn't find a valid model for Rank association.
Please provide the :class_name option on the association declaration.
If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.
```